version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    restart: unless-stopped
    ports:
      - "8085:8080"
    volumes:
      - /mnt/truenas_nfs/jenkins:/var/jenkins_home
